routes/web.php
<?php

use App\Http\Controllers\CidadesController;
use App\Http\Controllers\PostosController;
use App\Http\Controllers\PrecosController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ Relatórios ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Route::get('reports/precos', [PostosController::class, 'precos']);
Route::get('reports/postos', [CidadesController::class, 'postos']);

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ Middleware ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ CRUD ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Route::resource('cidades', CidadesController::class)->middleware('auth');
Route::resource('postos', PostosController::class)->middleware('auth');
Route::resource('precos', PrecosController::class)->middleware('auth');

app/Models/Postos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Cidades;
use App\Models\Precos;
use Illuminate\Http\Request;

class Postos extends Model
{
    protected $table = 'postos';
    protected $fillable = [
        'id',
        'nome',
        'endereco',
        'bairro',
        'bandeira',
        'razao_social',
        'cnpj',
        'cidade_id'
    ];

    public function cidades() {
        return $this->belongsTo(Cidades::class, 'cidade_id');
    }

    public function preco_postos() {
        return $this->hasMany(Precos::class);
    }

    static function paramsValidate(Request $request)
    {
        $rules = [
            'nome' => 'required|min:5|max:100',
            'endereco' => 'required|min:5|max:500',
            'bandeira' => 'required|min:2|max:100',
            'bairro' => 'required|min:5|max:100',
            'razao_social' => 'required|min:2|max:150',
            'cnpj' => 'required|min:14'
        ];

        $request->validate($rules);
    }
    use HasFactory;
}

app/Http/Controllers/PostosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cidades;
use App\Models\Postos;
use Illuminate\Http\Request;

class PostosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $postos = Postos::all();
        return view('postos/index', compact('postos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cidades = Cidades::all();
        return view('postos/register', compact('cidades'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Postos::paramsValidate($request);
        Postos::create($request->all());
        return redirect('postos');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Postos  $postos
     * @return \Illuminate\Http\Response
     */
    public function show(Postos $postos)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Postos  $postos
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $postos = Postos::find($id);
        $cidades = Cidades::all();
        return view('postos/editar', compact('postos', 'cidades'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Postos  $postos
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Postos::paramsValidate($request);

        $posto = Postos::find($id);
        $posto->update($request->all());
        return redirect('postos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Postos  $postos
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $posto = Postos::find($id);
        $posto->delete();
        return redirect('postos');
    }

    public function precos(Request $request){
        $postos = Postos::all();
        $selectedPosto = Postos::find($request->id);
        if(isset($selectedPosto->preco_postos)){
            $preco_postos = $selectedPosto->preco_postos;
        } else {
            $preco_postos = null;
        }
        return view('reports/precos', compact('postos', 'preco_postos'));
    }
}

resources/views/postos/editar.blade.php
@extends('layouts.main')

@section('title')
  Editar curso
@endsection

@section('content')
  <form
    class="d-flex flex-column bd-highlight mb-3 justify-content-center align-items-center"
    action="{{route('postos.update', $postos->id)}}"
    method="POST"
  >
    @csrf
    @method('PUT')
    <div class="form-group w-25 d-flex flex-column justify-content-center align-items-center">
      <label for="nome">Nome do Posto</label>
      <input type="text" name="nome" class="form-control" value="{{ $postos->nome }}"  />

      <label for="endereco">Endereço</label>
      <input type="text" name="endereco" class="form-control" value="{{ $postos->endereco }}" />

      <label label="bairro">Bairro</label>
      <input type="text" name="bairro" class="form-control" value="{{ $postos->bairro }}" />

      <label label="bandeira">Bandeira</label>
      <input type="text" name="bandeira" class="form-control" value="{{ $postos->bandeira }}" />

      <label label="razao_social">Razão Social</label>
      <input type="text" name="razao_social" class="form-control" value="{{ $postos->razao_social }}" />

      <label label="cnpj">CNPJ</label>
      <input type="text" name="cnpj" class="form-control" value="{{ $postos->cnpj }}" />

      <select
        name="cidade_id"
        id="cidade_id"
        class="form-control  mt-4"
      >
        @foreach ($cidades as $cidade)
            <option name="cidade_id" value="{{ $cidade->id }}">{{ $cidade->nome }}</option>
        @endforeach
      </select>
      <button type="submit" class="btn btn-primary pl-3 pr-3 mt-3">Enviar</button>
    </div>
  </form>
  @if ($errors->any())
    <div class="alert, alert-danger p-2">
      <strong>Não foi possível realizar cadastro, devido aos seguintes erros:</stro>
      <ul>
        @foreach ($errors->all() as $erro)
          <li>{{ $erro }}</li>
        @endforeach
      </ul>
    </div>
  @endif
@endsection

resources/views/postos/index.blade.php
@extends('layouts.main')

<style>
  th, td {
    padding: .2rem 1rem;
  }
</style>

@section('title')
  Postos
@endsection

@section('content')
  <section class="d-flex mt-4 justify-content-center align-center">
    <table class="table table-striped table-dark">
      <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Endereço</th>
        <th>Bairro</th>
        <th>Bandeira</th>
        <th>Razao Social</th>
        <th>CNPJ</th>
        <th>Cidade</th>
        <th>Editar</th>
        <th>Deletar</th>
      </tr>
      @foreach ($postos as $posto)
      <tr>
        <td>{{ $posto->id }}</td>
        <td>{{ $posto->nome }}</td>
        <td>{{ $posto->endereco }}</td>
        <td>{{ $posto->bairro }}</td>
        <td>{{ $posto->bandeira }}</td>
        <td>{{ $posto->razao_social }}</td>
        <td>{{ $posto->cnpj }}</td>
        <td>{{ $posto->cidades->nome }}</td>
        <td>
          <a
            href="{{url('postos/'.$posto->id.'/edit')}}"
            class="btn bg-primary border-none outline-none text-white"
          >
            Editar
          </a>
        </td>
        <td> 
          <form class="d-inline" action="{{ route('postos.destroy',$posto->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn bg-danger border-none outline-none text-white">Deletar</button>
          </form>
        </td>
      @endforeach
      </tr>
    </table>
  </section>
  <nav class="py-4 d-flex justify-content-center align-center">
    <a href="postos/create">Cadastrar</a>
  </nav>
@endsection

resources/views/postos/register.blade.php
@extends('layouts.main')

@section('title')
  Cadastrar Postos
@endsection

@section('content')
  <form
    class="d-flex flex-column bd-highlight mb-3 justify-content-center align-items-center"
    action="{{route('postos.store')}}"
    method="POST"
  >
    @csrf
    <div class="form-group w-25 d-flex flex-column justify-content-center align-items-center">
      <br>
      <label for="nome">Nome do Posto</label>
      <input type="text" name="nome" class="form-control" value="{{ old('nome') }}"  />

      <label for="endereco">Endereço</label>
      <input type="text" name="endereco" class="form-control" value="{{ old('endereco') }}" />

      <label label="bairro">Bairro</label>
      <input type="text" name="bairro" class="form-control" value="{{ old('bairro') }}" />

      <label label="bandeira">Bandeira</label>
      <input type="text" name="bandeira" class="form-control" value="{{ old('bandeira') }}" />

      <label label="razao_social">Razão Social</label>
      <input type="text" name="razao_social" class="form-control" value="{{ old('razao_social') }}" />

      <label label="cnpj">CNPJ</label>
      <input type="text" name="cnpj" class="form-control" value="{{ old('cnpj') }}" />

      <select
        name="cidade_id"
        id="cidade_id"
        class="form-control  mt-4"
      >
        @foreach ($cidades as $cidade)
            <option name="cidade_id" value="{{ $cidade->id }}">{{ $cidade->nome }}</option>
        @endforeach
      </select>

      <button type="submit" class="btn btn-primary pl-3 pr-3 mt-3">Enviar</button>
    </div>
  </form>
  @if ($errors->any())
    <div class="alert, alert-danger p-2">
      <strong>Não foi possível realizar cadastro, devido aos seguintes erros:</stro>
      <ul>
        @foreach ($errors->all() as $erro)
          <li>{{ $erro }}</li>
        @endforeach
      </ul>
    </div>
  @endif
@endsection