routes/web.php
<?php

use App\Http\Controllers\CidadesController;
use App\Http\Controllers\PostosController;
use App\Http\Controllers\PrecosController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ Relatórios ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Route::get('reports/precos', [PostosController::class, 'precos']);
Route::get('reports/postos', [CidadesController::class, 'postos']);

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ Middleware ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ CRUD ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Route::resource('cidades', CidadesController::class)->middleware('auth');
Route::resource('postos', PostosController::class)->middleware('auth');
Route::resource('precos', PrecosController::class)->middleware('auth');

app/Models/Cidades.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Postos;
use Illuminate\Http\Request;

class Cidades extends Model
{
    protected $table = 'cidades';
    protected $fillable = ['id', 'nome', 'uf', 'cep'];

    public function postos() {
        return $this->hasMany(Postos::class, 'cidade_id');
    }

    public static function paramsValidate(Request $request)
    {
        $rules = [
            'nome' => 'required|min:5|max:100',
            'uf' => 'required|min:2',
            'cep' => 'required',
        ];

        $request->validate($rules);
    }
    use HasFactory;
}

app/Http/Controllers/CidadesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cidades;
use Illuminate\Http\Request;

class CidadesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cidades = Cidades::all();
        return view('cidades/index', compact('cidades'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cidades/register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Cidades::paramsValidate($request);

        Cidades::create($request->all());
        return redirect('cidades');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Cidades  $cidades
     * @return \Illuminate\Http\Response
     */
    public function show(Cidades $cidades)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Cidades  $cidades
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cidade = Cidades::find($id);
        return view('cidades/editar', compact('cidade'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cidades  $cidades
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Cidades::paramsValidate($request);

        $cidade = Cidades::find($id);
        $cidade->update($request->all());
        return redirect('cidades');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Cidades  $cidades
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cidades $cidades, $id)
    {
        $cidade = Cidades::find($id);
        $cidade->delete();
        return redirect('cidades');
    }

    public function postos(Request $request){
        $cidades = Cidades::all();
        $selectedCity = Cidades::find($request->id);
        if(isset($selectedCity->postos)){
            $postos = $selectedCity->postos;
        } else {
            $postos = null;
        }
        return view('reports/postos', compact('cidades', 'postos'));
    }
}

resources/views/cidades/editar.blade.php
@extends('layouts.main')

@section('title')
  Editar curso
@endsection

@section('content')
  <form
    class="d-flex flex-column bd-highlight mb-3 justify-content-center align-items-center"
    action="{{route('cidades.update', $cidade->id)}}"
    method="POST"
  >
    @csrf
    @method('PUT')
    <label for="nome">Nome da Cidade</label>
    <input type="text" name="nome" value="{{ $cidade->nome }}"  />

    <label for="uf">Unidade Federativa (UF)</label>
    <input type="text" name="uf" value="{{ $cidade->uf }}" />

    <label label="cep">CEP</label>
    <input type="text" name="cep" value="{{ $cidade->cep }}" />

    <button type="submit" class="btn btn-primary pl-3 pr-3 mt-3">Enviar</button>
  </form>
  @if ($errors->any())
    <div class="alert, alert-danger p-2">
      <strong>Não foi possível realizar cadastro, devido aos seguintes erros:</stro>
      <ul>
        @foreach ($errors->all() as $erro)
          <li>{{ $erro }}</li>
        @endforeach
      </ul>
    </div>
  @endif
@endsection

resources/views/cidades/index.blade.php
@extends('layouts.main')

<style>
  th, td {
    padding: .2rem 1rem;
  }
</style>

@section('title')
  Cidades
@endsection

@section('content')
  <section class="d-flex mt-4 justify-content-center align-center">
    <table class="table table-striped table-dark">
      <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>UF</th>
        <th>CEP</th>
        <th>Editar</th>
        <th>Deletar</th>
      </tr>
      @foreach ($cidades as $cidade)
      <tr>
        <td>{{ $cidade->id }}</td>
        <td>{{ $cidade->nome }}</td>
        <td>{{ $cidade->uf }}</td>
        <td>{{ $cidade->cep }}</td>
        <td>
          <a
            href="{{url('cidades/'.$cidade->id.'/edit')}}"
            class="btn bg-primary border-none outline-none text-white"
          >
            Editar
          </a>
        </td>
        <td> 
          <form class="d-inline" action="{{ route('cidades.destroy',$cidade->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn bg-danger border-none outline-none text-white">Deletar</button>
          </form>
        </td>
      @endforeach
      </tr>
    </table>
  </section>
  <nav class="py-4 d-flex justify-content-center align-center">
    <a href="cidades/create">Cadastrar</a>
  </nav>
@endsection

resources/views/cidades/register.blade.php
@extends('layouts.main')

@section('title')
  Cadastrar cursos
@endsection

@section('content')
  <form
    class="d-flex flex-column bd-highlight mb-3 justify-content-center align-items-center"
    action="{{route('cidades.store')}}"
    method="POST"
  >
    @csrf
    <div class="form-group w-25 mt-4 d-flex flex-column justify-content-center align-items-center">
      <label for="nome" class="mt-2">Nome da Cidade</label>
      <input type="text" name="nome" class="form-control" value="{{ old('nome') }}"  />

      <label for="uf" class="mt-2">Unidade Federativa (UF)</label>
      <input type="text" name="uf" class="form-control" value="{{ old('uf') }}" />

      <label label="cep" class="mt-2">CEP</label>
      <input type="text" name="cep" pattern="\d{0,5}-\d{0,3}"  class="form-control" value="{{ old('cep') }}" />

      <button type="submit" class="btn btn-primary pl-3 pr-3 mt-3">Enviar</button>
    </div>
  </form>
  @if ($errors->any())
    <div class="alert, alert-danger p-2">
      <strong>Não foi possível realizar cadastro, devido aos seguintes erros:</stro>
      <ul>
        @foreach ($errors->all() as $erro)
          <li>{{ $erro }}</li>
        @endforeach
      </ul>
    </div>
  @endif
@endsection