routes/web.php
<?php

use App\Http\Controllers\CidadesController;
use App\Http\Controllers\PostosController;
use App\Http\Controllers\PrecosController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ Relatórios ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Route::get('reports/precos', [PostosController::class, 'precos']);
Route::get('reports/postos', [CidadesController::class, 'postos']);

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ Middleware ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/* ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ CRUD ▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐▐ */
Route::resource('cidades', CidadesController::class)->middleware('auth');
Route::resource('postos', PostosController::class)->middleware('auth');
Route::resource('precos', PrecosController::class)->middleware('auth');

app/Models/Precos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Postos;
use Illuminate\Http\Request;

class Precos extends Model
{
    protected $table = 'precos';
    protected $fillable = [
        'id',
        'tipo_combustivel',
        'data_coleta',
        'preco_venda',
        'postos_id',
    ];
    
    public function postos() {
        return $this->belongsTo(Postos::class, 'postos_id');
    }

    static function paramsValidate(Request $request)
    {
        $rules = [
            'tipo_combustivel' => 'required|min:5|max:100',
            'data_coleta' => 'required',
            'preco_venda' => 'required|min:2|max:10',
            'postos_id' => 'required',
        ];

        $request->validate($rules);
    }
    use HasFactory;
}

app/Http/Controllers/PrecosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Postos;
use App\Models\Precos;
use Illuminate\Http\Request;
use DateTime;

class PrecosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $precos = Precos::all();
        return view('precos/index', compact('precos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $postos = Postos::all();
        $now = new DateTime();
        $result = $now->format('Y-m-d H:i:s');
        return view('precos/register', compact('postos', 'result'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Precos::paramsValidate($request);

        Precos::create($request->all());
        return redirect('precos');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Precos  $precos
     * @return \Illuminate\Http\Response
     */
    public function show(Precos $precos)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Precos  $precos
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $precos = Precos::find($id);
        $postos = Postos::all();
        return view('precos/editar', compact('precos', 'postos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Precos  $precos
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Precos::paramsValidate($request);

        $preco = Precos::find($id);
        $preco->update($request->all());
        return redirect('precos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Precos  $precos
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $preco = Precos::find($id);
        $preco->delete();
        return redirect('precos');
    }
}

resources/views/precos/editar.blade.php
@extends('layouts.main')

@section('title')
  Editar curso
@endsection

@section('content')
  <form
    class="d-flex flex-column bd-highlight mb-3 justify-content-center align-items-center"
    action="{{route('precos.update', $precos->id)}}"
    method="POST"
  >
    @csrf
    @method('PUT')
    <div class="form-group w-25 d-flex flex-column justify-content-center align-items-center">
      <br>
      <label for="tipo_combustivel">Combustível</label>
      <input type="text" name="tipo_combustivel" class="form-control" value="{{ $precos->tipo_combustivel }}"  />

      <label for="data_coleta">Data de Coleta do Preço</label>
      <input type="text" name="data_coleta" class="form-control" value="{{ $precos->data_coleta }}" />

      <label label="preco_venda">Preço de Venda</label>
      <input type="text" name="preco_venda" class="form-control" value="{{ $precos->preco_venda }}" />

      <label label="postos_id" class="mt-4">Posto de Combustível</label>
      <select
        name="postos_id"
        id="postos_id"
        class="form-control"
      >
        @foreach ($postos as $posto)
            <option name="postos_id" value="{{ $posto->id }}">{{ $posto->nome }}</option>
        @endforeach
      </select>

      <button type="submit" class="btn btn-primary pl-3 pr-3 mt-3">Enviar</button>
    </div>
  </form>
  @if ($errors->any())
    <div class="alert, alert-danger p-2">
      <strong>Não foi possível realizar cadastro, devido aos seguintes erros:</stro>
      <ul>
        @foreach ($errors->all() as $erro)
          <li>{{ $erro }}</li>
        @endforeach
      </ul>
    </div>
  @endif
@endsection

resources/views/precos/index.blade.php
@extends('layouts.main')

<style>
  th, td {
    padding: .2rem 1rem;
  }
</style>

@section('title')
  Preços
@endsection

@section('content')
  <section class="d-flex mt-4 justify-content-center align-center">
    <table class="table table-striped table-dark">
      <tr>
        <th>Id</th>
        <th>Combustível</th>
        <th>Data de Coleta</th>
        <th>Preço de Venda</th>
        <th>Posto</th>
        <th>Editar</th>
        <th>Deletar</th>
      </tr>
     @if ($precos ?? '' != null)
        @foreach ($precos as $preco)
        <tr>
          <td>{{ $preco->id }}</td>
          <td>{{ $preco->tipo_combustivel }}</td>
          <td>{{ $preco->data_coleta }}</td>
          <td>{{ $preco->preco_venda }}</td>
          <td>{{ $preco->postos->nome }}</td>
          <td>
            <a
              href="{{url('precos/'.$preco->id.'/edit')}}"
              class="btn bg-primary border-none outline-none text-white"
            >
              Editar
            </a>
          </td>
          <td> 
            <form class="d-inline" action="{{ route('precos.destroy',$preco->id) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn bg-danger border-none outline-none text-white">Deletar</button>
            </form>
          </td>
        @endforeach
     @endif
      </tr>
    </table>
  </section>
  <nav class="py-4 d-flex justify-content-center align-center">
    <a href="precos/create">Cadastrar</a>
  </nav>
@endsection

resources/views/precos/register.blade.php
@extends('layouts.main')

@section('title')
  Cadastrar Preços
@endsection

@section('content')
  <form
    class="d-flex flex-column bd-highlight mb-3 justify-content-center align-items-center"
    action="{{route('precos.store')}}"
    method="POST"
  >
    @csrf
    <div class="form-group w-25 d-flex flex-column justify-content-center align-items-center">
      <br>
      <label for="tipo_combustivel">Combustível</label>
      <input type="text" name="tipo_combustivel" class="form-control" value="{{ old('tipo_combustivel') }}"  />

      <label for="data_coleta">Data de Coleta do Preço</label>
      <input type="text" name="data_coleta" class="form-control" value="{{ $result }}" />

      <label label="preco_venda">Preço de Venda</label>
      <input type="text" name="preco_venda" class="form-control" value="{{ old('preco_venda') }}" />

      <label label="postos_id" class="mt-4">Posto de Combustível</label>
      <select
        name="postos_id"
        id="postos_id"
        class="form-control"
      >
        @foreach ($postos as $posto)
            <option name="postos_id" value="{{ $posto->id }}">{{ $posto->nome  }} - ({{ $posto->cidades->nome }})</option>
        @endforeach
      </select>

      <button type="submit" class="btn btn-primary pl-3 pr-3 mt-3">Enviar</button>
    </div>
  </form>
  @if ($errors->any())
    <div class="alert, alert-danger p-2">
      <strong>Não foi possível realizar cadastro, devido aos seguintes erros:</stro>
      <ul>
        @foreach ($errors->all() as $erro)
          <li>{{ $erro }}</li>
        @endforeach
      </ul>
    </div>
  @endif
@endsection